### ISSUE TITLE
Weights of CLS model

### ISSUE THREAD

**Issue by JavierRojas8** [hachreak/movad#1]
Hello, I am interested in using your model. I am wondering when could be avalible model's weight  

thanks

**Comment by hachreak** [comment]
Hi @JavierRojas8 ,
sorry for the long delay for the reply and thank you very much to show interest on our model.
We'll let you know soon in the next days about the model's weights, because we made a big code cleaning and refactoring after we finish the paper to make "presentable" the code.
Thanks to be patient.

**Comment by hachreak** [comment]
Hi @JavierRojas8 
finally, I had enough time to publish the [pretrained](https://github.com/IMPLabUniPr/movad/releases/tag/v1.0)! :D
